export const sheetCategories = [
  "Array & Hashing",
  "Matrix",
  "String",
  "Searching & Sorting",
  "LInkedlist",
  "Binary Trees",
  "Binary Search Trees",
  "Greedy",
  "Backtracking",
  "Stacks & Queues",
  "Heap",
  "Graph",
  "Trie",
  "Dynamic Programming",
  "Bit Manipulation",
]
